### NumPy SUM Operation

In [9]:
import numpy as np

In [10]:
arr = [[1, 2, 3],
       [4, 5, 6]]
arr = np.array(arr)

In [11]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr.sum()

21

In [13]:
arr.sum(axis=0)

array([5, 7, 9])

In [14]:
arr.sum(axis=1)

array([ 6, 15])

In [15]:
arr.sum(axis=1,keepdims = True)

array([[ 6],
       [15]])