### Import TensorFlow Library

In [2]:
import tensorflow as tf

C:\Users\ACER-PC\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\ACER-PC\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\ACER-PC\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\ACER-PC\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:496: FutureWarnin

In [102]:
import numpy as np

# CONSTANTS

### Example - 1

In [91]:
x = tf.constant([1,2,3,4,5])
y = tf.constant([6,7,8,9,10])

result = tf.multiply(x,y)

sess = tf.Session()

print(sess.run(result))

sess.close()

[ 6 14 24 36 50]


### Example - 2

In [97]:
constant_int_tensor = tf.constant(-255, shape=[1, 2, 3], dtype="int32")  # Rows = 1 * 2 = 2, Columns = 3

In [98]:
sess = tf.Session()

print(sess.run(constant_int_tensor))

sess.close()

[[[-255 -255 -255]
  [-255 -255 -255]]]


### Example- 3

In [99]:
# Constant 1-D Tensor from a python list.
con = tf.constant([1, 2, 3, 4, 5, 6])

In [100]:
sess = tf.Session()

print(sess.run(con))

sess.close()

[1 2 3 4 5 6]


### Example-4

In [103]:
# Or a numpy array
a = np.array([[1, 2, 3], [4, 5, 6]])
con = tf.constant(a)

In [104]:
sess = tf.Session()

print(sess.run(con))

sess.close()

[[1 2 3]
 [4 5 6]]


### Example - 5

In [105]:
## If dtype is specified the resulting tensor values are cast to the requested dtype.

In [106]:
con = tf.constant([1, 2, 3, 4, 5, 6], dtype=tf.float64)

In [107]:
sess = tf.Session()

print(sess.run(con))

sess.close()

[1. 2. 3. 4. 5. 6.]


### Example - 6

In [131]:
## If shape is set, the value is reshaped to match. Scalars are expanded to fill the shape:

In [132]:
con = tf.constant(0, shape=(2, 3))

In [133]:
sess = tf.Session()

print(sess.run(con))

sess.close()

[[0 0 0]
 [0 0 0]]


### Example - 7

In [115]:
con = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])

In [116]:
sess = tf.Session()

print(sess.run(con))

sess.close()

[[1 2 3]
 [4 5 6]]


### Example - 8

In [126]:
con = tf.constant(0, shape=(2,3,4))    # Rows = 2 * 3 = 6, Columns = 4

In [127]:
sess = tf.Session()

print(sess.run(con))

sess.close()

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


### Example - 9

In [129]:
con = tf.constant(3.14, shape=(3,3,2))  # Rows = 3 * 3 = 9, Columns = 2

In [130]:
sess = tf.Session()

print(sess.run(con))

sess.close()

[[[3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]]

 [[3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]]

 [[3.14 3.14]
  [3.14 3.14]
  [3.14 3.14]]]


# VARIABLE

In [72]:
## https://www.programcreek.com/python/example/90565/tensorflow.Variable

### Example-1

In [18]:
# Create two variables.
weights = tf.Variable(tf.random_normal([784, 200], stddev=0.35),
                      name="weights")
biases = tf.Variable(tf.zeros([200]), name="biases")

In [19]:
# Add an op to initialize the variables.
init_op = tf.global_variables_initializer()

In [38]:
# Later, when launching the model
with tf.Session() as sess:
    # Run the init operation.
    sess.run(init_op)
    sess.run(weights)

### Example-2

In [50]:
sess = tf.InteractiveSession()

In [51]:
weights = tf.Variable(tf.random_normal([784, 200], stddev=0.35),name="weights")

In [52]:
init = tf.global_variables_initializer()

In [53]:
sess.run(init)

In [54]:
sess.run(weights)

array([[-0.15465184,  0.18335058, -0.07036453, ..., -0.39243442,
        -0.37406108,  0.53162366],
       [ 0.2965579 ,  0.08951422, -0.00283159, ...,  0.21699037,
         0.46465027, -0.52953154],
       [ 0.12565038,  0.09330397, -0.20765725, ...,  0.37460318,
        -0.42643216, -0.24896105],
       ...,
       [-0.2308113 , -0.27522197,  0.1269986 , ..., -0.11684905,
        -0.05493119,  0.4048699 ],
       [ 0.47814807, -0.00242532, -0.19398347, ...,  0.06324185,
         0.16181786,  0.0870809 ],
       [ 0.08436053,  0.13001888,  0.2358265 , ..., -0.24181142,
        -0.3422968 , -0.04870958]], dtype=float32)

In [44]:
sess.run(weights).shape

(784, 200)

### Example-3

In [55]:
biases = tf.Variable(tf.zeros([200]), name="biases")

In [56]:
init = tf.global_variables_initializer()

In [57]:
sess = tf.InteractiveSession()

In [58]:
sess.run(init)

In [59]:
sess.run(biases)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [60]:
sess.run(biases).shape

(200,)

### Example-4

In [ ]:
biases = tf.Variable(tf.zeros([200]), name="biases")

In [61]:
init = tf.global_variables_initializer()

In [64]:
with tf.Session() as sess:
    # Run the init operation.
    ini = sess.run(init)
    var = sess.run(biases)
    print(ini)
    print(var)

None
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]


### Example-5

In [74]:
tensorX = tf.constant([1.5, 2.5, 3.5])
variableA = tf.Variable(tensorX, name="variableA")
variableB = tf.Variable([10, 20.5, 30.5], name="variableB")
variableC = tf.Variable(["US", "UK"], name="variableC")
variableD = tf.Variable([variableA, variableB], name="variableD")

In [75]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
 
print(sess.run(variableA))
print(sess.run(variableB))
print(sess.run(variableC))
print(sess.run(variableD))

[1.5 2.5 3.5]
[10.  20.5 30.5]
[b'US' b'UK']
[[ 1.5  2.5  3.5]
 [10.  20.5 30.5]]


### Variable Assignment

In [76]:
## In order to update, increment and decrement value of Variable, we use 
## Variable.assign(), 
## Variable.assign_add() and 
## Variable.assign_sub() methods respectively.

In [77]:
# Create a variable
variableA = tf.Variable(10, name="variableA")
 
# Start a session
sess = tf.Session()
 
# Initialization operation
init = tf.global_variables_initializer()
 
# Initialize variable
sess.run(init)
 
# Print session variable
print(sess.run(variableA))
 
# Assign new value to variable
sess.run(variableA.assign(20))
print(sess.run(variableA))
 
# Increment by 20
sess.run(variableA.assign_add(20))
print(sess.run(variableA))
 
# Decrement by 5
sess.run(variableA.assign_sub(5))
print(sess.run(variableA))

10
20
40
35


### Example-6

In [21]:
sess = tf.InteractiveSession()

In [22]:
tensorA = tf.random_uniform((4,4),1,2)

In [23]:
tensorA

<tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>

In [24]:
tensor_var_A = tf.Variable(initial_value = tensorA)

In [25]:
tensor_var_A

<tf.Variable 'Variable_1:0' shape=(4, 4) dtype=float32_ref>

In [26]:
sess.run(tensor_var_A)

FailedPreconditionError: Attempting to use uninitialized value Variable_1
	 [[Node: _retval_Variable_1_0_0 = _Retval[T=DT_FLOAT, index=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable_1)]]

In [28]:
# So, the error is saying that FailedPreconditionError: Attempting to use uninitialized value Variable.

# That means, we need to first initialize the TensorFlow variable and then we can run that variable.

# So, let’s do that first. Write the following code in the next cell.

In [29]:
init = tf.global_variables_initializer()

In [30]:
init

<tf.Operation 'init_3' type=NoOp>

In [31]:
sess.run(init)

In [32]:
sess.run(tensor_var_A)

array([[1.2528303, 1.5187039, 1.4886576, 1.0084516],
       [1.2130737, 1.9572936, 1.797703 , 1.0897057],
       [1.2622633, 1.9680562, 1.0070848, 1.9535785],
       [1.1924638, 1.4775044, 1.6700883, 1.3845856]], dtype=float32)

# PLACEHOLDER

In [84]:
init = tf.global_variables_initializer()
sess = tf.InteractiveSession()
sess.run(init)

### Example-1

In [85]:
tfph = tf.placeholder(tf.float32, shape=(None, 5))

In [86]:
# The above code creates a TensorFlow placeholder, and its datatype is float32, 
# and here None is the placeholder’s initial value of data. 
# As time goes and our machine learning mode starts training, the data is filled in the placeholder. 
# But, at the starting point, it is None.

In [90]:
a = tf.placeholder(tf.float32, name='k')
b = tf.placeholder(tf.float32, name='l')
c = tf.add(a, b, name='c')
sess.run(c, feed_dict={a: 2.1, b: 1.9})

4.0

### Example-2

In [78]:
x = tf.placeholder(tf.float32,None)

In [79]:
y = x * 2

In [80]:
with tf.Session() as sess:
    result = sess.run(y , feed_dict = {x : [1 , 2 , 3]})
    print(result)

[2. 4. 6.]


### Example - 3

In [81]:
x = tf.placeholder("float", [None, 3])
y = x * 2

with tf.Session() as session:
    x_data = [[1, 2, 3],
              [4, 5, 6],]
    result = session.run(y, feed_dict={x: x_data})
    print(result)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [82]:
## The first dimension of the placeholder is None, meaning we can have any number of rows.
## The second dimension is fixed at 3, meaning each row needs to have three columns of data.