In [47]:
import numpy as np 
import pandas as pd
from scipy.optimize import curve_fit 

In [3]:
x_data = [10,20,30,40,50,60,100]
y_data = [1,2,3,4,5,6,7]

In [4]:
def test(x, a, b): 
    return a * np.sin(b * x)

In [5]:
param, param_cov = curve_fit(test,x_data,y_data) 
print("Sine funcion coefficients:") 
print(param) 
print("Covariance of coefficients:") 
print(param_cov)

Sine funcion coefficients:
[0.83102679 1.02234959]
Covariance of coefficients:
[[6.06027510e+00 3.22848743e-03]
 [3.22848743e-03 1.16264547e-02]]


In [42]:
x_data = [6,5,4,3,2,1,0]
y_data = [420,420,420,420,420,420,420]

In [43]:
#x_data = [2,0,0,0,0,0,0]
#y_data = [1,2,3,4,5,6,7]

In [44]:
lin_fit = np.polyfit(x_data, y_data, 1)
m = lin_fit[0]

In [45]:
lin_fit

array([-3.22092785e-14,  4.20000000e+02])

In [11]:
m

0.003571428571428571

In [35]:
    def lin_param(x):
        x_data = np.arange(0, len(x))[::-1]
        print(x_data)
        y_data = np.array(x)
        print(y_data)
        lin_fit = np.polyfit(x_data, y_data, 1)
        print(lin_fit)
        m = lin_fit[0]
        #return m

In [50]:
x_data = [6 ,5 ,4 ,3 ,2 ,1 ,0]
y_data = [420.0 ,420.0 ,420.0 ,420.0 ,420.0 ,420.0 ,420.0]

In [51]:
lin_fit = np.polyfit(x_data, y_data, 1)
m = lin_fit[0]

In [52]:
print(lin_fit)

[-3.22092785e-14  4.20000000e+02]


In [53]:
print(m)

-3.220927848393343e-14


In [40]:
np.array(y_data)

array([420., 420., 420., 420., 420., 420., 420.])

In [41]:
lin_param(y_data)

[6 5 4 3 2 1 0]
[420. 420. 420. 420. 420. 420. 420.]
[-3.22092785e-14  4.20000000e+02]


In [48]:
df = pd.DataFrame(data = y_data,columns=['trend_score'])
df

trend_score
0          420
1          420
2          420
3          420
4          420
5          420
6          420

In [49]:
lin_param(df['trend_score'])

[6 5 4 3 2 1 0]
[420 420 420 420 420 420 420]
[-3.22092785e-14  4.20000000e+02]


In [54]:
x_data = [6 ,5 ,4 ,3 ,2 ,1 ,0]
y_data = [2. ,0. ,0. ,0. ,0. ,0. ,0.]

In [55]:
lin_fit = np.polyfit(x_data, y_data, 1)
print(lin_fit)

[ 0.21428571 -0.35714286]
