# Applying Sigmoid Function to a Matrix

In [1]:
from numpy import array, exp

#### Example-1

In [9]:
z = array([ 0.2, 0.4, 0.1])
print('z = ', z)

z =  [0.2 0.4 0.1]


#### Applying Sigmoid

In [10]:
g = 1 / (1 + exp(-z))
print('g = ', g)

g =  [0.549834   0.59868766 0.52497919]


#### Example-2

In [11]:
z = array([[0.2, 0.4], [0.5, 0.7], [0.9, .004]])
print('z = ', z)

z =  [[0.2   0.4  ]
 [0.5   0.7  ]
 [0.9   0.004]]


In [12]:
g = 1 / (1 + exp(-z))
print('g =', g)

g = [[0.549834   0.59868766]
 [0.62245933 0.66818777]
 [0.7109495  0.501     ]]


#### Example-3

In [13]:
z = array([ 0, 0, 0])
print('z = ', z)

z =  [0 0 0]


#### Applying Sigmoid

In [14]:
g = 1 / (1 + exp(-z))
print('g = ', g)

g =  [0.5 0.5 0.5]


#### Example-4

In [17]:
z = array([ 1, 1, 1])
print('z = ', z)

z =  [1 1 1]


#### Applying Sigmoid

In [18]:
g = 1 / (1 + exp(-z))
print('g = ', g)

g =  [0.73105858 0.73105858 0.73105858]


#### Example-5

In [19]:
z = array([ 100, 200, 350])
print('z = ', z)

z =  [100 200 350]


#### Applying Sigmoid

In [20]:
g = 1 / (1 + exp(-z))
print('g = ', g)

g =  [1. 1. 1.]


# Word To Vectorization

In [66]:
from gensim.test.utils import common_texts

In [67]:
from gensim.sklearn_api import W2VTransformer

In [68]:
# Create a model to represent each word by a 10 dimensional vector.
model = W2VTransformer(size=5, min_count=1, seed=1)

In [69]:
# What is the vector representation of the word 'graph'?
wordvecs = model.fit(common_texts).transform(['graph', 'system'])

In [70]:
wordvecs.shape

(2, 5)

In [71]:
print(wordvecs)

[[ 0.026413    0.08820025  0.06650764  0.07490228  0.01024412]
 [ 0.09892886  0.06905331  0.01773284 -0.04928733 -0.0942073 ]]


In [72]:
common_texts.append(['king','queen','poor','man','women'])

In [73]:
common_texts

[['human', 'interface', 'computer'],
 ['survey', 'user', 'computer', 'system', 'response', 'time'],
 ['eps', 'user', 'interface', 'system'],
 ['system', 'human', 'system', 'eps'],
 ['user', 'response', 'time'],
 ['trees'],
 ['graph', 'trees'],
 ['graph', 'minors', 'trees'],
 ['graph', 'minors', 'survey'],
 ['king', 'queen', 'poor'],
 ['king', 'queen', 'poor', 'man', 'women'],
 ['king', 'queen', 'poor', 'man', 'women'],
 ['king', 'queen', 'poor', 'man', 'women'],
 ['king', 'queen', 'poor', 'man', 'women']]

In [74]:
wordvecs_king = model.fit(common_texts).transform(['king'])

In [75]:
wordvecs_king

array([[ 0.05366261, -0.07302203, -0.0226953 ,  0.03719609,  0.00524206]],
      dtype=float32)

In [76]:
wordvecs_queen = model.fit(common_texts).transform(['queen'])

In [77]:
wordvecs_queen

array([[-0.04391805, -0.08197114,  0.07048977,  0.06331532,  0.00784916]],
      dtype=float32)

In [78]:
wordvecs_man = model.fit(common_texts).transform(['man'])

In [79]:
wordvecs_man

array([[-0.03659304,  0.00946495, -0.05504789,  0.09364089,  0.02008053]],
      dtype=float32)

In [80]:
wordvecs_women = model.fit(common_texts).transform(['women'])

In [81]:
wordvecs_women

array([[-0.09349911,  0.01334542, -0.09202823, -0.07974752,  0.07572836]],
      dtype=float32)

In [82]:
wordvecs_king - wordvecs_man + wordvecs_queen

array([[ 0.0463376 , -0.16445813,  0.10284236,  0.00687052, -0.00698932]],
      dtype=float32)