## Reshaping The Numpy Array

In [4]:
import numpy as np
import pandas as pd

#### First Input

In [9]:
x = [[282.5       ,   0.        , 166.025],
    [251.77      ,   0.        , 166.025],
    [0.        , 238.7       ,   0.],
    [ 0.        , 324.99      ,   0.]]
x = np.array(x)
x

array([[282.5  ,   0.   , 166.025],
       [251.77 ,   0.   , 166.025],
       [  0.   , 238.7  ,   0.   ],
       [  0.   , 324.99 ,   0.   ]])

In [10]:
print(x.shape)

(4, 3)


#### Second Input

In [13]:
y = [1,2,3,4]
y = np.array(y)
y

array([1, 2, 3, 4])

In [14]:
print(y.shape)

(4,)


#### Reshape the 'y' input

In [16]:
y_reshape = y.reshape(4,1)
y_reshape

array([[1],
       [2],
       [3],
       [4]])

#### Concatenate Two Numpy Array

In [22]:
x_y_data = np.concatenate((x,y_reshape),axis=1)
x_y_data

array([[282.5  ,   0.   , 166.025,   1.   ],
       [251.77 ,   0.   , 166.025,   2.   ],
       [  0.   , 238.7  ,   0.   ,   3.   ],
       [  0.   , 324.99 ,   0.   ,   4.   ]])

#### Converting Into DataFrame

In [24]:
pd.DataFrame(data=x_y_data,columns=['A','B','C','D'])

A       B        C    D
0  282.50    0.00  166.025  1.0
1  251.77    0.00  166.025  2.0
2    0.00  238.70    0.000  3.0
3    0.00  324.99    0.000  4.0