In [89]:
#Metrix Similarity Calculation
#Auther: Subrat Kumar Sahoo

In [30]:
import pandas as pd
import numpy as np
import scipy as sp
import itertools
import array
from scipy import spatial

In [95]:
age    = [20,20,35,45,55,60]
height = [5.5,5.6,5.8,5.7,5.9,6.0]
weight = [50,50,60,65,74,80]

In [96]:
df = pd.DataFrame({'age':age,
                  'height':height,
                  'weight':weight})
df

age  height  weight
0   20     5.5      50
1   20     5.6      50
2   35     5.8      60
3   45     5.7      65
4   55     5.9      74
5   60     6.0      80

### Euclidean Similarity

In [97]:
Y = spatial.distance.pdist(df, 'euclidean')

In [98]:
Y

array([ 0.1       , 18.03025236, 29.15544546, 42.4400754 , 50.00249994,
       18.02886574, 29.15493097, 42.4392507 , 50.00159997, 11.18078709,
       24.41331604, 32.01624588, 13.45511055, 21.21532465,  7.81088983])

In [99]:
spatial.distance.squareform(Y)

array([[ 0.        ,  0.1       , 18.03025236, 29.15544546, 42.4400754 ,
        50.00249994],
       [ 0.1       ,  0.        , 18.02886574, 29.15493097, 42.4392507 ,
        50.00159997],
       [18.03025236, 18.02886574,  0.        , 11.18078709, 24.41331604,
        32.01624588],
       [29.15544546, 29.15493097, 11.18078709,  0.        , 13.45511055,
        21.21532465],
       [42.4400754 , 42.4392507 , 24.41331604, 13.45511055,  0.        ,
         7.81088983],
       [50.00249994, 50.00159997, 32.01624588, 21.21532465,  7.81088983,
         0.        ]])

### braycurtis Similarity

In [77]:
Y = spatial.distance.pdist(df, 'braycurtis')

In [78]:
Y

array([0.00066181, 0.14350539, 0.21025105, 0.28231939, 0.31828442,
       0.14285714, 0.2096184 , 0.28171021, 0.31768953, 0.06974596,
       0.14467543, 0.18314425, 0.07661612, 0.11578143, 0.03951584])

In [79]:
spatial.distance.squareform(Y)

array([[0.        , 0.00066181, 0.14350539, 0.21025105, 0.28231939,
        0.31828442],
       [0.00066181, 0.        , 0.14285714, 0.2096184 , 0.28171021,
        0.31768953],
       [0.14350539, 0.14285714, 0.        , 0.06974596, 0.14467543,
        0.18314425],
       [0.21025105, 0.2096184 , 0.06974596, 0.        , 0.07661612,
        0.11578143],
       [0.28231939, 0.28171021, 0.14467543, 0.07661612, 0.        ,
        0.03951584],
       [0.31828442, 0.31768953, 0.18314425, 0.11578143, 0.03951584,
        0.        ]])

## canberra Similarity

In [80]:
Y = spatial.distance.pdist(df, 'canberra')

In [81]:
Y

array([0.00900901, 0.39018504, 0.53290731, 0.69530277, 0.77424749,
       0.38118022, 0.52389972, 0.68630201, 0.76525199, 0.17369565,
       0.33524684, 0.42296419, 0.18198958, 0.27194644, 0.09084266])

In [82]:
spatial.distance.squareform(Y)

array([[0.        , 0.00900901, 0.39018504, 0.53290731, 0.69530277,
        0.77424749],
       [0.00900901, 0.        , 0.38118022, 0.52389972, 0.68630201,
        0.76525199],
       [0.39018504, 0.38118022, 0.        , 0.17369565, 0.33524684,
        0.42296419],
       [0.53290731, 0.52389972, 0.17369565, 0.        , 0.18198958,
        0.27194644],
       [0.69530277, 0.68630201, 0.33524684, 0.18198958, 0.        ,
        0.09084266],
       [0.77424749, 0.76525199, 0.42296419, 0.27194644, 0.09084266,
        0.        ]])

# yule Similarity

In [83]:
Y = spatial.distance.pdist(df, 'yule')

In [84]:
Y

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan])

In [85]:
spatial.distance.squareform(Y)

array([[ 0., nan, nan, nan, nan, nan],
       [nan,  0., nan, nan, nan, nan],
       [nan, nan,  0., nan, nan, nan],
       [nan, nan, nan,  0., nan, nan],
       [nan, nan, nan, nan,  0., nan],
       [nan, nan, nan, nan, nan,  0.]])

### cosine Similarity

In [86]:
Y = spatial.distance.pdist(df, 'cosine')

In [87]:
Y

array([1.68808588e-06, 1.09453254e-02, 2.54631147e-02, 3.37429800e-02,
       3.50205360e-02, 1.09789161e-02, 2.55148198e-02, 3.38079914e-02,
       3.50926340e-02, 3.04536044e-03, 6.31825662e-03, 6.89251868e-03,
       5.94997829e-04, 7.89671912e-04, 1.72766715e-05])

In [88]:
spatial.distance.squareform(Y)

array([[0.00000000e+00, 1.68808588e-06, 1.09453254e-02, 2.54631147e-02,
        3.37429800e-02, 3.50205360e-02],
       [1.68808588e-06, 0.00000000e+00, 1.09789161e-02, 2.55148198e-02,
        3.38079914e-02, 3.50926340e-02],
       [1.09453254e-02, 1.09789161e-02, 0.00000000e+00, 3.04536044e-03,
        6.31825662e-03, 6.89251868e-03],
       [2.54631147e-02, 2.55148198e-02, 3.04536044e-03, 0.00000000e+00,
        5.94997829e-04, 7.89671912e-04],
       [3.37429800e-02, 3.38079914e-02, 6.31825662e-03, 5.94997829e-04,
        0.00000000e+00, 1.72766715e-05],
       [3.50205360e-02, 3.50926340e-02, 6.89251868e-03, 7.89671912e-04,
        1.72766715e-05, 0.00000000e+00]])